{{- if and .Values.frontend.enabled .Values.frontend.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "momo-store.fullname" . }}-frontend-config
  labels:
    app: frontend
    {{- include "momo-store.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.frontend.configmap.data | nindent 2 }}
{{- end }}