{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "momo-store.fullname" . }}-backend
  labels:
    app: backend
    {{- include "momo-store.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        {{- include "momo-store.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: backend
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.backend.service.targetPort }}
          name: http
        env:
          {{- toYaml .Values.backend.env | nindent 10 }}
        {{- if .Values.backend.configmap.enabled }}
        envFrom:
        - configMapRef:
            name: {{ include "momo-store.fullname" . }}-backend-config
        {{- end }}
        {{- with .Values.backend.probes }}
        livenessProbe:
          httpGet:
            path: {{ .liveness.path }}
            port: {{ .liveness.port }}
          initialDelaySeconds: {{ .liveness.initialDelaySeconds }}
          periodSeconds: {{ .liveness.periodSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .readiness.path }}
            port: {{ .readiness.port }}
          initialDelaySeconds: {{ .readiness.initialDelaySeconds }}
          periodSeconds: {{ .readiness.periodSeconds }}
        {{- end }}
        resources:
          {{- toYaml .Values.backend.resources | nindent 10 }}
{{- end }}