global:
  imagePullSecrets:
    - name: ycr-secret

backend:
  replicaCount: 1
  image:
    tag: 1.1.0

frontend:
  replicaCount: 1
  s3:
    endpoint: "storage.yandexcloud.net"
    bucket: "momo-store-frontend"
    prefix: "momo-store"

ingress:
  enabled: true
  hosts:
    - host: ""
      paths:
        - path: /api
          pathType: Prefix
          service: backend
          port: 8081
        - path: /
          pathType: Prefix
          service: frontend
          port: 80
