# Overrides for production environment

replicaCount: 1

image:
  tag: 1.1.0
  pullPolicy: Always

resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 1000m
    memory: 1Gi

env:
  - name: NODE_ENV
    value: "production"
  - name: API_URL
    value: "http://backend-prod:8080/api"

ingress:
  enabled: true
  hosts:
    - host: frontend.example.com
      paths:
        - path: /
          pathType: Prefix